AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC Endpoint Template for DynamoDB'

Parameters:
  ClientName:
    Type: String
    Description: "Client Name"
  CreatedBy:
    Type: String
    Description: "Created By"
  ProjectName:
    Type: String
    Description: "Name of the project"
  VPCId:
    Type: String
    Description: "ID of the VPC where the endpoint will be created"
  PrivateRouteTableId:
    Type: CommaDelimitedList
    Description: "List of private subnet IDs"

Resources:
  VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.dynamodb"
      VpcEndpointType: Gateway
      RouteTableIds: !Ref PrivateRouteTableId
      Tags:
        - Key: Name
          Value: !Sub ${ClientName}-dynamodb-endpoint
        - Key: ClientName
          Value: !Ref ClientName
        - Key: CreatedBy
          Value: !Ref CreatedBy
        - Key: ProjectName
          Value: !Ref ProjectName

  VPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for VPC Endpoint"
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0" # Adjust this as per your security requirements
      Tags:
        - Key: ClientName
          Value: !Ref ClientName
        - Key: CreatedBy
          Value: !Ref CreatedBy
        - Key: ProjectName
          Value: !Ref ProjectName

Outputs:
  VPCEndpointId:
    Value: !Ref VPCEndpoint
    Description: "The ID of the VPC Endpoint"
  VPCEndpointSecurityGroupId:
    Value: !Ref VPCEndpointSecurityGroup
    Description: "The ID of the VPC Endpoint SecurityGroup"
